### ISSUE TITLE
Breaking react server side rendering?

### ISSUE THREAD

**Issue by shaimo** [desandro/eventie#14]
The line

```
var elem = document.querySelector('#my-elem');
```

uses document which is not defined on the server side. This means server side rendering of components that use imagesloaded or react-masonry-component (and thus depend on eventie) would fail. Am I missing anything?

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm sorry to say I do not have any React expertise. I'd appreciate if someone else can chime in with a knowledgeable response.
