### ISSUE TITLE
'this' context breaks ie8 using browserify.

### ISSUE THREAD

**Issue by cwbutler** [desandro/eventie#8]
In eventie.js, this context is an empty object on ie8.
```javascript
( function( window ) {
...
})( this );
```

To fix, change 'this' to 'window' and everybody is happy again:
```javascript
( function( window ) {
...
})( window );
```

I noticed this issue using your other library 'doc-ready.js'. In that source code, it requires 'eventie.js'. It seems that 'doc-ready' has already replaced 'this' with 'window':

https://github.com/desandro/doc-ready/pull/5

**Comment by desandro** [comment]
Thanks so much for this contribution and for pointing to my previous decree :grin: I've merged your PR and pushed a new tag `v1.0.6`
